# -*- coding: utf-8 -*-
"""brainflow_realtime_snr.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i03sjMxO29oWUSJiitXJL84D6DJbnX1_
"""

!pip install brainflow

import time
import numpy as np
from brainflow.board_shim import BoardShim, BrainFlowInputParams

board_id = -1
params = BrainFlowInputParams()
board = BoardShim(board_id, params)
board.prepare_session()
board.start_stream()

try:
    while True:
        time.sleep(1)
        data = board.get_board_data(250)
        if data.size == 0:
            continue
        eeg_channels = BoardShim.get_eeg_channels(board_id)
        for ch in eeg_channels:
            signal = data[ch]
            noise = np.random.normal(0, 0.1, signal.size)  # Add small Gaussian noise
            signal_noisy = signal + noise
            snr = 10 * np.log10(np.var(signal) / np.var(signal_noisy - signal))
            print(f"Ch {ch}: SNR = {snr:.2f} dB")
            if snr < 10:
                print(f"Alert: Ch {ch} low quality!")
except KeyboardInterrupt:
    board.stop_stream()
    board.release_session()