# -*- coding: utf-8 -*-
"""fMRI_MVPA_classifier.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3UiggIMsd3m9F2cZsk-VLmU3uaG_r_H
"""

!pip install nilearn mne

from nilearn import datasets, decoding
from sklearn.model_selection import cross_val_score
import numpy as np


haxby = datasets.fetch_haxby()
fmri = haxby.func[0]
labels = np.loadtxt(haxby.session_target[0], str, skiprows=1, usecols=1)[:100]  # Face vs. object, 100 trials
mask = haxby.mask_vt[0]  # Ventral temporal mask

# MVPA (ML + Neuroimaging)
decoder = decoding.Decoder(mask=mask, cv=5, estimator='svc')
X = mne.io.read_raw_fif(fmri, preload=True).get_data()[:100]  # Simplified—adjust slicing
decoder.fit(fmri, labels)
scores = cross_val_score(decoder, X, labels, cv=5)
print(f"Mean CV accuracy: {np.mean(scores):.2f}")