# -*- coding: utf-8 -*-
"""fmri_motion_viz.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOhLaNz1xHipdviWgIZltWyUIo4I1_8p
"""

!pip install nilearn

from nilearn import datasets, plotting
from nilearn.image import resample_img
import matplotlib.pyplot as plt

# Load Haxby
haxby = datasets.fetch_haxby()
fmri_img = haxby.func[0]

# Motion Correction (Signal Processing)
from nilearn.image import smooth_img
corrected_img = smooth_img(fmri_img, fwhm=None)  # Placeholder—real motion correction needs MCFLIRT or similar
mean_img = resample_img(corrected_img, target_affine=corrected_img.affine, interpolation='nearest').slicer[:, :, :, :1]

# Visualize
plotting.plot_stat_map(mean_img, title="Motion-Corrected fMRI - Haxby")
plt.show()