# -*- coding: utf-8 -*-
"""fmri_mean_image_visualizer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZfcHc3xHSmL8invb0EyfLYTaItLWacH
"""

!pip install nilearn

from nilearn import datasets, plotting
import matplotlib.pyplot as plt

# Load Haxby dataset (Neuroimaging)
haxby = datasets.fetch_haxby()
fmri_img = haxby.func[0]  # First subject’s fMRI

# Mean image (Signal Processing)
from nilearn.image import mean_img
mean_fmri = mean_img(fmri_img)
print(f"Mean fMRI shape: {mean_fmri.shape}")

# Visualize
plotting.plot_stat_map(mean_fmri, title="Mean fMRI - Haxby Subject 1")
plt.show()

plotting.plot_stat_map(mean_fmri, title="Axial View", display_mode='z')